spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hm_music_box
    username: postgres
    password: qawqae102103

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
